### ISSUE TITLE
Measurement code error

### ISSUE THREAD

**Issue by G1iderK** [GiggleLiu/QuantumPEPS.jl#3]
Hi @GiggleLiu , when I run the notebook about QuantumPEPS, the measurement operation code `   Measure{nbit, 1, AbstractBlock}(Z, (loc,), 0, false)` can not work, I notice that you have provided a basis rotation approach instead, however, I am not sure what should I do to replace the measurement code? Could you please provide a simple demo about it? Thanks.

**Comment by GiggleLiu** [comment]
Thanks for your interest in this notebook, however, the notebook is quite outdated.
Please check this one in the example folder of QuAlgorithmZoo: https://github.com/QuantumBFS/QuAlgorithmZoo.jl/tree/master/examples/QMPS 

Let me know if it still has issue.
